name: Bower
description: the official [bower](http://bower.io) module for [crystal](https://crystal.sh)
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: https://crystal.sh
copyright: 2015 Crystal
modules:
  crystal/authors-file: v0.1.0
  crystal/json-stringify: v0.1.0
  crystal/license-mit: v0.1.0
  crystal/readme-md: v0.1.0
imports:
  authors: crystal/authors-file.Generator
  json-trans: crystal/json-stringify.Transformer
  license: crystal/license-mit.Generator
  readme: crystal/readme-md.Generator
exports:
  Generator:
    filename: .bowerrc
    schema: config.yml
    transformer: json-trans
    type: generator
  Schematic:
    schema: config.yml
    type: schematic
outputs:
  - generator: authors
    spec:
      author: $author
      name: $name
  - generator: license
    spec:
      copyright: $copyright
  - generator: readme
    spec:
      name: $name
      version: $version
      description: $description