name: Bower
description: the official [bower](http://bower.io) module for [crystal](https://crystal.sh)
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: https://crystal.sh
copyright: 2015 Crystal
modules:
  crystal/authors-file: ~0.1.0
  crystal/json-stringify: ~0.1.0
  crystal/license-mit: ~0.1.0
  crystal/readme-md: ~0.1.0
exports:
  Generator:
    filename: .bowerrc
    schema: config.yml
    transformer: json-stringify.Transformer
    type: generator
  Schematic:
    schema: config.yml
    type: schematic
outputs:
  - generator: authors-file.Generator
    spec:
      author: $author
      name: $name
  - generator: license-mit.Generator
    spec:
      copyright: $copyright
  - generator: readme-md.Generator
    spec:
      name: $name
      version: $version
      description: $description