name: Bower
description: official [Bower](http://bower.io) module of [Crystal](https://crystal.sh)
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: https://crystal.sh
copyright: 2015 Crystal
modules:
  crystal/authors: ~0.2.3
  crystal/json: ~0.3.1
  crystal/license: ~0.2.3
  crystal/readme: ~0.2.1
exports:
  ConfigGenerator:
    engine: crystal/json/StringifyEngine
    filename: .bowerrc
    schema: config.yml
    type: generator
  ConfigSchematic:
    schema: config.yml
    type: schematic
  PackageGenerator:
    engine: crystal/json/StringifyEngine
    filename: bower.json
    schema: package.yml
    type: generator
  PackageSchematic:
    schema: package.yml
    type: schematic
outputs:
  - generator: crystal/authors/generator
    spec:
      author: $author
      name: $name
      
  - generator: crystal/license/mit-generator
    spec:
      copyright: $copyright
      
  - generator: crystal/readme/generator
    spec:
      name: $name
      description: $description