name: Bower
description: official [Bower](http://bower.io) module of [Crystal](https://crystal.sh)
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: https://crystal.sh
copyright: 2015 Crystal
imports:
  crystal/authors: ~0.2.3
  crystal/crystal-readme: ~0.1.5
  crystal/json: ~0.3.1
  crystal/license: ~0.2.3
exports:
  ConfigGenerator:
    description: Generates a `.bowerrc` file.
    engine: json.StringifyEngine
    example: config-generator
    filename: .bowerrc
    schema: config.yml
    type: generator
  ConfigSchematic:
    description: Schema for `.bowerrc` files.
    schema: config.yml
    type: schematic
  PackageGenerator:
    description: Generates a `bower.json` file.
    engine: json.StringifyEngine
    example: package-generator
    filename: bower.json
    schema: package.yml
    type: generator
  PackageSchematic:
    description: Schema for `bower.json` files.
    schema: package.yml
    type: schematic
outputs:
  - generator: authors.AuthorsGenerator
    spec:
      author: $author
      name: $name
      
  - generator: license.MITGenerator
    spec:
      copyright: $copyright
      
  - generator: crystal-readme.ModuleReadmeGenerator
    spec:
      name: $name
      description: $description
      exports: $exports
      repo: crystal/bower