name: Bower
version: 0.1.0
description: 'generator / schema of `bower.json` and `.bowerrc` for [Bower](http://bower.io)'
keywords:
  - bower
  - package manager
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: 'https://crystal.sh'
copyright: 2015 Crystal
imports:
  crystal/authors: ~0.3.3
  crystal/crystal-readme: ~0.2.0
  crystal/json: ~0.4.0
  crystal/license: ~0.3.1
  crystal/npm: ~0.3.1
  crystal/jshint: latest
  crystal/bower: latest
  crystal/docker: latest
  crystal/vagrant: latest
exports:
  ConfigGenerator:
    description: Generates a `.bowerrc` file.
    engine: json.StringifyEngine
    example: config-generator
    filename: .bowerrc
    schema: config.yml
    type: generator
  ConfigSchematic:
    description: Schema for `.bowerrc` files.
    schema: config.yml
    type: schematic
  PackageGenerator:
    description: Generates a `bower.json` file.
    engine: json.StringifyEngine
    example: package-generator
    filename: bower.json
    schema: package.yml
    type: generator
  PackageSchema:
    description: Schema for `bower.json` files.
    schema: package.yml
    type: schema
outputs:
  - generator: authors.AuthorsGenerator
    spec:
      author: $author
      name: $name
  - generator: license.MITGenerator
    spec:
      copyright: $copyright
  - generator: crystal-readme.ModuleReadmeGenerator
    spec:
      name: $name
      description: $description
      exports: $exports
      repo: crystal/bower
  - generator: npm.PackageGenerator
    spec:
      version: $version
      name: $name
      description: $description
  - generator: jshint.ConfigGenerator
  - generator: bower.PackageGenerator
    spec:
      description: $description
      keywords: $keywords
  - generator: bower.ConfigGenerator
  - generator: vagrant.VagrantfileGenerator
url: 'http://bower.io'
