modules:
  bower.config: v0.1.0
imports:
  bower: bower.config.Generator
outputs:
  - generator: bower
    spec:
      directory: app/components/
      analytics: false
      timeout: 120000
      registry:
        search:
          - http://localhost:8000
          - https://bower.herokuapp.com