imports:
  crystal/bower: latest
outputs:
  - generator: bower.ConfigGenerator
    spec:
      directory: app/components/
      analytics: false
      timeout: 120000
      registry:
        search:
          - http://localhost:8000
          - https://bower.herokuapp.com